apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: tesseractmachine
      labels:
        app: tesseractmachine
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: tesseractmachine
      template:
        metadata:
          labels:
            app: tesseractmachine
        spec:
          containers:
            - name: tesseractmachine
              image: ryangrahamnc/tesseractmachine:latest
              ports:
                - containerPort: 1120
              resources:
                requests:
                  cpu: "1m"
                  memory: "1Mi"
                limits:
                  cpu: "500m"
                  memory: "500Mi"




  - apiVersion: v1
    kind: Service
    metadata:
      name: tesseractmachine-service
    spec:
      selector:
        app: tesseractmachine
      ports:
        - protocol: TCP
          port: 1120
          targetPort: 1120


